### ISSUE TITLE
Reach out to Turing comms tell them about the project.

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/TuringDataStories#1]

**Comment by kevinxufs** [comment]
Got a response from the Turing head of comms and they said they were interested and looking to meet next week.

**Comment by DavidBeavan** [comment]
Meeting on 2020-07-15 15:30. Next steps:

### Strand 1: How to describe the work in an accessible way and how others want to contribute to that, Mark and Beth happy to work with us after:
* Work up prototype further
* Think about different audiences strands (code, data science, analysis)
* How to make those strands accessible, where someone comes for one and leaves with knowledge of other two
	
### Strand2: Who else within and outside of Turing can help in practical terms, story generation or peer review, Mark and Beth again can help connect?
Potentials (all unapproached) are:
* Nick Holliman (Turing and Newcastle)https://www.turing.ac.uk/people/researchers/nick-holliman, Visualisation Interest Group. He's well connected to data journalism. @DavidBeavan knows him
* Tomas Petricek and The Gamma https://thegamma.net/
* David Blood, FT? https://www.ft.com/david-blood
* Link up with journalist would be amazing!
* [@DavidBeavan comment, we might be wanting to forge new ground beyond visualisation]
