### ISSUE TITLE
Fastpages presentation improvements

### ISSUE THREAD

**Issue by samvanstroud** [alan-turing-institute/TuringDataStories#103]
On the fastpages:

- [x] Story Tags
- [x] Snippets underneath title on the homepage
- [x] Image next to title on the homepage.
- [x] Fix first story

**Comment by kevinxufs** [comment]
The current fast page looks really good @samvanstroud  and great to see that there will be even more improvements coming.

One thing I wanted to note was that in all of our guidance, vision documentation about the project, we talk about our stories being jupyter notebooks. I understand the fast page is of course based off of these notebooks, but was wondering if there will be any confusion here?
