### ISSUE TITLE
Reformat our README so that it immediately provides direction to potential contributors

### ISSUE THREAD

**Issue by kevinxufs** [alan-turing-institute/TuringDataStories#106]
### Summary

As suggested by Alison, we will presumably be linking our Github (in particular the README) to potential contributors. Especially for those who may not have much experience using Github, we want to be able to immediately support them.

### What needs to be done?

Rewrite README.

This could be about adding a first paragraph along the lines of 'Interested in contributing? Click here' which would link to a more detail contribution guidelines page. I say more detailed, because we would also need to edit that with formal roles and so on.

**Comment by samvanstroud** [comment]
See discussion at #90
