### ISSUE TITLE
Launch the project

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/TuringDataStories#109]
### Summary

We should decide when to officially launch our project (which means to start making noise about it).

### What needs to be done?

- [x] Have at least one story published
- [x] Have a paragraph describing which kind of contributions we are seeking (read comments from Alisson in #101 and #106) @samvanstroud 
- [x] Add the above to readme and fastpages
- [x] Link contributor to twitter account (@crangelsmith)
- [x] Write a few twitter thread about the project and the existing stories. @crangelsmith 
- [x] Write a short text that we could reuse to cross post on slack channels, emails, etc.  @crangelsmith 
- [x] Ethics approval. 
- [ ] Speak to comms again #80 
- [ ] Neaten up the project board, closing issues etc
- [ ] If we use one URL: fastpages landing page https://alan-turing-institute.github.io/TuringDataStories-fastpages/

Any date in mind for this?

### Who can help?

@kevinxufs @crangelsmith @samvanstroud @DavidBeavan 

Please feel free to add any other tasks that we must do before the launch.

---

### Updates

Decided to officially launch our the 16th December. We'll do all the posting on out usual meeting that day.

**Comment by DavidBeavan** [comment]
A potential blocker on launch: we need to [seek ethical approval](https://turingcomplete.topdesk.net/tas/public/ssp/content/detail/service?unid=cb5e35246f474d1f90abae8ea262338c) for our story, or understand if we are exempt for some reason. My reading is that all projects need ethical approval (before starting really). Having engaged in the process recently elsewhere, we must follow proper process.

**Comment by DavidBeavan** [comment]
Can someone sound out #ethics-advisory-group on Slack and see? But I think all projects need ethical approval, and particularly those involving data collected from people, like the initial story

**Comment by crangelsmith** [comment]
Thanks @DavidBeavan for bringing this up! Would this mean that we need to get approval from the Turing each time a story gets published? This sounds unsustainable. Something that would make more sense to me is that the review process of the story include some ethical considerations in line with the ones of the Turing and we apply for ethical approval once for the general scope of the project and the ethical guidelines.

**Comment by DavidBeavan** [comment]
> Would this mean that we need to get approval from the Turing each time a story gets published? This sounds unsustainable.

I agree, and some institutions only require ethical approval for project with data from or on human subjects. We must check, though, the Turing is super responsible and rightfully so. For now, though, we should reach out. I can, but it would have to be next week

**Comment by crangelsmith** [comment]
> I agree, and some institutions only require ethical approval for project with data from or on human subjects. We must check, though, the Turing is super responsible and rightfully so. For now, though, we should reach out. I can, but it would have to be next week

Thanks @DavidBeavan I agree with you. Let's emphasise that we are only using open data in this project (and for the foreseeable future), so the data probably already passed an ethical approval before publishing. 

As today is my last day before the break I'm trying to finish up all work related things and I don't have time to follow this up this week, but if you post on the slack next week I'll keep an eye on it as well.

**Comment by samvanstroud** [comment]
Thanks for flagging this David.
I link to a first draft of contributor text :
https://github.com/alan-turing-institute/TuringDataStories/issues/90#issuecomment-743165581

**Comment by crangelsmith** [comment]
Draft for a [launch twitter thread] (https://hackmd.io/@VTC7yAqQRpezaQv_KTSPJQ/ryTenvD2v/edit)

**Comment by crangelsmith** [comment]
Now that we have EAG approval we must discuss again when to do our official launch. Let's discuss this on the meeting of 12 of May.

**Comment by samvanstroud** [comment]
We might want a more pretty domain ready for the launch:
- Get a domain (Dave to follow up on funding this?)
- Configure the github page for use with a custom domain: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site
- Modify some fastpages config

**Comment by crangelsmith** [comment]
We can say that the project has been launched, even if it was a soft one. I will close this issue.
