### ISSUE TITLE
Outline Lighting talk on 26th May 

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/TuringDataStories#12]
[Slides, as given](https://github.com/alan-turing-institute/TuringDataStories/blob/master/outputs/talks/20200526_Covid19DevTeam_REG_Talk.pptx?raw=true)

Plan, assuming 10 min slot (out of that is time for Qs):

* Dave: 1min Genesis of Covid19DevTeam
    - REG Project Development Service Area
    - Desire to make a difference in the fight against Covid-19
    - Had approaches from various external collaborators
    - Formed Covid19DevTeam to pool efforts of REGers and to channel our 22 days time
    - Overlaps with Open Source Service Area, Knowledge Sharing Service Area, Communications Service Area
* Camila 1m: What is a Turing Data Story?  From the Readme (https://github.com/alan-turing-institute/TuringDataStories):
    - About the project
    - What is a Turing Data Story? Principles.
* Sam: First story - Question we want to answer:
    - Will the relaxation of lockdown disproportionately affect those in more deprived areas? (Due to an assumption that people in these areas will be more likely to have to physically go to work and not be able to work remotely, putting them at higher risk).
     - Are this (or other) trends reflected in the data from Scotland vs data from England?
* Sam: 1min discussion of available data:
    - Weekly mortality counts broken down by local area. Not age standardised.
    - Index of Multiple Deprevation dataset
    - No data is availible on the spatial distribution of testing rates. Can we get access to testing data? FOA request?
*
* Dave: 1 min demo of existing code
    - Coronavirus (COVID-19) Visualise and Map
    - https://github.com/DavidBeavan/coronavirus_covid-19
* Someone
    - Join us as #Covid19DevTeam on Slack
    - And TuringDataStories in the Turing GitHub org
    - Q&A

**Comment by kevinxufs** [comment]
Create a folder to put the slides in.

**Comment by DavidBeavan** [comment]
Slides uploaded: https://github.com/alan-turing-institute/TuringDataStories/blob/master/outputs/talks/20200526_Covid19DevTeam_REG_Talk.pptx?raw=true
