### ISSUE TITLE
Decide our project norms and ways of working

### ISSUE THREAD

**Issue by DavidBeavan** [alan-turing-institute/TuringDataStories#13]
Such as:

* Working with others (do we go 100% open source and open data)?
* How do we try to licence our work (the group prefers non-commercial)?
* Attribution/authorship (us, I presume?), across the whole thing?
* We do not endorse derivative code, works or narratives
* more...

**Comment by DavidBeavan** [comment]
Licence, suggest:

## Creative Commons Attribution-NonCommercial
CC BY-NC

> This license lets others remix, adapt, and build upon your work non-commercially, and although their new works must also acknowledge you and be non-commercial, they don’t have to license their derivative works on the same terms.

[View License Deed](https://creativecommons.org/licenses/by-nc/4.0) | [View Legal Code](https://creativecommons.org/licenses/by-nc/4.0/legalcode)

OR, stricter on reuse:

## Creative Commons Attribution-NonCommercial-ShareAlike
CC BY-NC-SA 

> This license lets others remix, adapt, and build upon your work non-commercially, as long as they credit you and license their new creations under the identical terms.

[View License Deed](https://creativecommons.org/licenses/by-nc-sa/4.0) | [View Legal Code](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode)

**Comment by DavidBeavan** [comment]
## Authorship and citation

Suggest:
* alphabetical and all of us, everywhere. AKA 'shared co-first authorship'
* prep (or point to in README) who did/does what
* We produce a 'cite us as...' and distribute it carefully everywhere ;) i.e. make it easy to be cited

**Comment by kevinxufs** [comment]
Just a thought - as we're taking some inspiration from The Turing Way, do we also want to have a code of conduct?

**Comment by martintoreilly** [comment]
+💯on code of conduct. I'd also suggest borrowing other good practice items from Turing WAy, especially a contributors file / table following the "[all contributors](https://github.com/all-contributors/all-contributors)" model and a contributors guide.

**Comment by DavidBeavan** [comment]
For max points, there are [whole charters](https://www.researchgate.net/publication/221441546_The_iterative_design_of_a_project_charter_for_interdisciplinary_research) that cover how we play nicely.

**Comment by kevinxufs** [comment]
Have now added a code of conduct file, borrowed from Turing Way

**Comment by DavidBeavan** [comment]
Discussions on 2020-10-07 between @DavidBeavan @crangelsmith @samvanstroud suggests we adopt [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).
