### ISSUE TITLE
Open data projects talk with BEIS

### ISSUE THREAD

**Issue by kevinxufs** [alan-turing-institute/TuringDataStories#131]
### Summary

I'd like to arrange for us to present our project with some of the Civil Servants in the Department of Business, Energy and Industrial Strategy (BEIS).

I think its a really good opportunity for us to share some of our work. Civil Servants I think would fit within our target readership audience and I think it's generally important for Civil Servants to upskill their data fluency. We could also potentially build a network that might be relevant for certain data stories of the future.

### What needs to be done?

I need to arrange a date for this, although I expect it to be around the end of April.

I'm expecting it to be relatively casual discussion around things like Open data, data journalism and community. I'd like for us to share a bit more around the journey and community building aspect of Turing Data Stories, as well as showcase some of the stories we have and that are in the pipeline. I see it a little bit more as a teach-in about building open source projects as opposed to specifically about our stories.

### Who can help?

I think if possible it would be great to have at least 3 of us there from the TDS side (more is welcome too). Will provide a wider perspective. 

I don't anticipate that we'll need to do too much prep - we could potentially use some of the slides we currently have, but I'd like to leave it to be relatively casual. (This is just my current BEIS team).

I'm of course happy to lead and do all the organisation for this.

**Comment by kevinxufs** [comment]
@DavidBeavan @crangelsmith @samvanstroud 

I've uploaded the slides now to the share point - let me know if you can't access.

Feel free to make any changes as well. I mentioned previously but it would be good if you guys are able to lead most of the discussion as you will be our honorary guest speakers! I'm happy to give an introduction to the work and invite you guys to speak but otherwise will be a bit more quiet.

**Comment by kevinxufs** [comment]
Hi guys, this link should hopefully work now: https://thealanturininstitute.sharepoint.com/:p:/r/sites/TuringDataStories/_layouts/15/Doc.aspx?sourcedoc=%7BBBD3975D-FF97-4883-AAAC-C45956A7A1E8%7D&file=Turing%20Data%20Stories%20BRE%20presentation.pptx&action=edit&mobileredirect=true

Just in terms of a structure:

- I'll open and invite everyone to give an introduction, with Dave talking a bit around the Turing and REG.
- I'll then do Slides 1+2  (intro / vision
- Sam slides 3-5
- Dave slides 6-8
- Camila slides 9-12

I can facilitate that Q&A at the end as well.

**Comment by crangelsmith** [comment]
This happened successfully on the 29th of April.
