### ISSUE TITLE
Invite to participate in Turing Lunch and Learns

### ISSUE THREAD

**Issue by DavidBeavan** [alan-turing-institute/TuringDataStories#136]
### Summary

Email from Nick M at Turing 2021-04-19:
> ... we are looking to host a series of lunch and learn sessions for the Turing community. At the moment the plan is one a month and they’d last an hour – I was speaking with M last week and they said that you’ve been doing really interesting work with the Turing Data Stories ...
>  
> Was wondering whether you would be interested in this at all?

### What needs to be done?

- [ ] Discuss if we are interested
- [ ] Next steps

### Who can help?

* All

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by crangelsmith** [comment]
This didn't happen. Will open the issue again in another opportunity presents itself.
