### ISSUE TITLE
SeptembRSE Submission

### ISSUE THREAD

**Issue by edaub** [alan-turing-institute/TuringDataStories#148]
### Summary

Submit an abstract for the RSE conference?

https://septembrse.society-rse.org/calls/

### What needs to be done?

- [ ] Read details and write an abstract

### Who can help?

* @edaub 

---

**Comment by crangelsmith** [comment]
Great, thank you for opening this issue @edaub! Should we submit a talk? A walkthrough could also be an option (then we would have to focus on a particular story(is) I think?). What does everyone think?

**Comment by samvanstroud** [comment]
A workshop could be interesting!
- Present the project (10-15mins)
- Run through a story (10-15mins)
- Split into teams and work on stories

For the last section, we could come up with some ideas for stories, make sure the data is available, and then put people into breakout rooms while they begin hacking around the data

**Comment by samvanstroud** [comment]
@crangelsmith  and I are writing an application here:
https://hackmd.io/C992WBKmTX-N7ahdRu0sDA?both

**Comment by crangelsmith** [comment]
Workshop submitted on 2nd July. Fingers crossed!
