### ISSUE TITLE
Credit newbies for their input

### ISSUE THREAD

**Issue by DavidBeavan** [alan-turing-institute/TuringDataStories#151]
### Summary
Give credit (via all contributors) to new collaborators.

### What needs to be done?

- [x] Gather list of names
- [x] Gather list of contributions (there is a [taxonomy](https://allcontributors.org/docs/en/emoji-key))
- [x] Use the [bot](https://allcontributors.org/docs/en/bot/usage) to add names (one by one)

### Who can help?

* All/any

---

**Comment by DavidBeavan** [comment]
@helendduncan

**Comment by ChristinaLast** [comment]
@ChristinaLast - reviewer (pending) so far!

**Comment by lukehare** [comment]
@lukehare - review (also pending!)

**Comment by DavidBeavan** [comment]
@all-contributors please add @helendduncan for code, data, ideas, projectManagement, review, content

**Comment by DavidBeavan** [comment]
@all-contributors please add @ChristinaLast for code, data, ideas, review, content

**Comment by DavidBeavan** [comment]
@all-contributors please add @lukehare  for code, data, ideas, review, content

**Comment by DavidBeavan** [comment]
@all-contributors please add @ChristinaLast for code, data, ideas, review, content

**Comment by DavidBeavan** [comment]
> @ChristinaLast already contributed before to code, data, ideas, review, content

Bad bot, that would be true if I did things in the ask, merge order; but I didn't, did I

**Comment by DavidBeavan** [comment]
@all-contributors please add @ChristinaLast for code, data, ideas, review, content

**Comment by DavidBeavan** [comment]
@all-contributors please add @lukehare for code, data, ideas, review, content

**Comment by DavidBeavan** [comment]
Lemme know if I've missed anyone or missed off any attributions
