### ISSUE TITLE
[Review] Desert Island Discs 

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/TuringDataStories#166]
# Story Review: 
**Story Name:**  Desert Island Discs 

**Submitting Author:** @helendduncan @billfinnegan @samvanstroud @lukehare @crangelsmith 

**Pull Request:** #165 

**Reviewers:** @edwardchalstrey1 @mhauru

## Reviewer instructions & questions

@edwardchalstrey1 @mhauru, please carry out your review in this issue by updating the checklist below, and writing new comments in case you have any questions. Please share the tasks between the both of you, no need to replicate work.  If you cannot edit the checklist please:

- Make sure you're logged in to your GitHub account
- Be sure to accept the invite at this URL: https://github.com/alan-turing-institute/TuringDataStories/settings/access

Any questions, concerns or suggestions regarding the review process please let @crangelsmith, @DavidBeavan or @samvanstroud know.

✨ Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest ✨

#### Code of conduct
- [x] I confirm that I read and will adhere to the Turing Data Stories [code of conduct](https://github.com/alan-turing-institute/TuringDataStories/blob/master/CODE_OF_CONDUCT.md).

#### General checks
- [x]  **Notebook:** Is the source code for this data story available as a notebook in the linked pull request?
- [x]  **Contribution and authorship:** Are the authors clearly listed? Does the author list seem appropriate and complete?
- [x] **Scope and eligibility:** Does the submission contain an original and complete analysis of open data? Is the story aligned with the Turing Data Stories [vision statement](https://github.com/alan-turing-institute/TuringDataStories#our-vision)?

#### Reproducibility
- [x] Does the notebook run in a local environment?
- [ ] Does the notebook build and run in binder?
- [x] Are all data sources openly accessible and properly cited with a link?
- [x] Are the data [open](https://opendatahandbook.org/guide/en/what-is-open-data/), and do they have an explicit licence, provenance and attribution?

#### Pedagogy
- [x] Does the story demonstrate some specific data analysis or visualisation techniques?
- [x] Are these techniques well-motivated?
- [x] Are these techniques well implemented?
- [x] Is the notebook well documented, using both markdown cells and comments in code cells?
- [x] Does the notebook has an introduction section motivating the story?
- [x] Does the notebook has a conclusion section discussing the main insight from the stories?
- [x] Is the paper well written (it does not require editing for structure, language, or writing quality)? <- **EC:** see Markus comments below and mine on the PR

#### Context
- [x] Does the story give an insight into some societal issue?
- [x] Is the context around this issue well referenced (newspaper articles, scientific papers, etc.)?

#### Ethical 

- [x] Is any linkage of datasets in the story likely to lead to an increased risk of the personal identification of individuals?
- [x] Is the Story truthful and clear about any limitations of the analysis (and potential biases in data)?
- [x] Is the Story unlikely to lead to negative social outcomes, such as (but not limited to) increasing discrimination or injustice?

## AOB

- The PR has already a list of TO-DOs that are currently being worked on.
- If you have comments on the text you can use ReviewNB to write them in the right places.

**Comment by edwardchalstrey1** [comment]
@mhauru perhaps we can work though this together some time next week?

**Comment by mhauru** [comment]
The original data set by Gustar (https://hcommons.org/deposits/item/hc:37503/) is published under CC-BY-NC-SA, but the derivative data set made specifically for this notebook (https://hcommons.org/deposits/item/hc:42511/) is under CC0 (Public Domain). Is that an issue, given that the original license has the "share alike" clause which seems to suggest any derivative works should be under the same license? See e.g. https://creativecommons.org/faq/

Also, I tried to check what Spotify says about releasing things based on their genre data, but got lost in legalese I didn't understand. Have you looked into this?

Otherwise happy with the openness of the data.

**Comment by mhauru** [comment]
A few typos: "hop-hop", "avalaible", "simplication", "conected"

Would recommend running a spell-checker, easy and fast to get rid of small things like that.

**Comment by mhauru** [comment]
The text for one of the profession plots explains the profession "erudite", but "erudite" is not actually in the plot any more.

**Comment by mhauru** [comment]
>This count of total and repeat castaways is a little less than at the top of this notebook. As we are using a dataframe that has been merged with other data sources (Wikpedia, Spotify) we have lost some castaways where there was missing information. This shouldn't impact the analysis below.

The last sentence could use a bit more justification. Even a comment about how only a small amount of information is missing would do it, although if you have actual numbers for how much was lost, even better.

**Comment by mhauru** [comment]
Maybe you're aware of this, but one section still says
>TODO Finish this section

**Comment by edwardchalstrey1** [comment]
Overall, very well written and interesting story, well done! 👍
