### ISSUE TITLE
Update README with new contributors

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/TuringDataStories#188]
### Summary

We are a bit behind in recognising all the contributors to the project. Also the @allcontributors bot seems to be broken. 

### What needs to be done?

- [ ] Fix the @allcontributors bot 
- [ ] Add new contributors (new reviewers and story authors).

### Who can help?

Anyone in the team.

**Comment by lukehare** [comment]
I think the all-contributors config is just missing some brackets. I've opened a PR #189 to fix!
