### ISSUE TITLE
[Review] Overwatch story

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/TuringDataStories#219]
# Story Review: 

**Story Name:** [Esports analysis: Overwatch](https://github.com/alan-turing-institute/TuringDataStories/issues/163)

**Submitting Author: @mhauru @kevinxufs 

**Pull Request:** #163

**Reviewers:** @jack89roberts  @llewelld  

## Reviewer instructions & questions

 @jack89roberts,  @llewelld, please carry out your review in this issue by updating the checklist below, and writing new comments in case you have any questions. If you cannot edit the checklist please:

- Make sure you're logged in to your GitHub account
- Be sure to accept the invite at this URL: https://github.com/alan-turing-institute/TuringDataStories/settings/access

Any questions, concerns or suggestions regarding the review process please let @crangelsmith, @DavidBeavan or @samvanstroud know.

✨ Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest ✨

#### Code of conduct
- [ ] I confirm that I read and will adhere to the Turing Data Stories [code of conduct](https://github.com/alan-turing-institute/TuringDataStories/blob/master/CODE_OF_CONDUCT.md).

#### General checks
- [ ]  **Notebook:** Is the source code for this data story available as a notebook in the linked pull request?
- [ ]  **Contribution and authorship:** Are the authors clearly listed? Does the author list seem appropriate and complete?
- [ ] **Scope and eligibility:** Does the submission contain an original and complete analysis of open data? Is the story aligned with the Turing Data Stories [vision statement](https://github.com/alan-turing-institute/TuringDataStories#our-vision)?

#### Reproducibility
- [ ] Does the notebook run in a local environment?
- [ ] Does the notebook build and run in binder?
- [ ] Are all data sources openly accessible and properly cited with a link?
- [ ] Are the data [open](https://opendatahandbook.org/guide/en/what-is-open-data/), and do they have an explicit licence, provenance and attribution?

#### Pedagogy
- [ ] Does the story demonstrate some specific data analysis or visualisation techniques?
- [ ] Are these techniques well motivated?
- [ ] Are these techniques well implemented?
- [ ] Is the notebook well documented, using both markdown cells and comments in code cells?
- [ ] Does the notebook has a introduction section motivating the story?
- [ ] Does the notebook has a conclusion section discussing the main insight from the stories?
- [ ] Is the paper well written (it does not require editing for structure, language, or writing quality)?

#### Context
- [ ] Does the story give an insight into some societal issue?
- [ ] Is the context around this issue well referenced (newspaper articles, scientific papers, etc.)?

#### Ethical 

- [ ] Is any linkage of datasets in the story unlikely to lead to an increased risk of the personal identification of individuals?
- [ ] Is the Story truthful and clear about any limitations of the analysis (and potential biases in data)?
- [ ] Is the Story unlikely to lead to negative social outcomes, such as (but not limited to) increasing discrimination or injustice?

**Comment by AoifeHughes** [comment]
Great, thanks!

 @jack89roberts how'd you like to do this? Shall we independently review + make notes, then have a chat / update the checklist? Happy to do whatever suits!

**Comment by jack89roberts** [comment]
Sure, let's each read through it then we can compare notes. I'll try to read it in the next week or so.

**Comment by jack89roberts** [comment]
Markus, Kevin et al.: I'm going to start adding comments to the PR as I read through but you can wait to look through them until me and Aoife have caught up about it.

**Comment by mhauru** [comment]
Thanks everyone, new story is now published: https://alan-turing-institute.github.io/TuringDataStories/stories/2023-02-01-Overwatch-League/OWL_story.html
