### ISSUE TITLE
Migration from fast-pages to Quarto

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/TuringDataStories#233]
### Summary

Fast pages have been deprecated. We plan to move to Quarto, as well as move the deployment of the blog into this repo. 

For reference, here is where the fastpages blog lived https://github.com/alan-turing-institute/TuringDataStories-fastpages/tree/master

### What needs to be done?

- [ ] Quarto based schelenton in this repo
- [ ] Github action deployment of the main branch.

### Who can help?

Wonderful @phinate and @yongrenjie have volunteered to help

---

**Comment by phinate** [comment]
Closing as resolved by #246 (thanks for your help @yongrenjie @crangelsmith!)
