### ISSUE TITLE
Wrangle Data

### ISSUE THREAD

**Issue by samvanstroud** [alan-turing-institute/TuringDataStories#30]
Datasets:

- Mortality counts https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/causesofdeath/datasets/deathregistrationsandoccurrencesbylocalauthorityandhealthboard
- IMD https://www.gov.uk/government/statistics/english-indices-of-deprivation-2019

**Comment by samvanstroud** [comment]
- [ ] Combine IMD for MSOAs to LA level
- [ ] Convert to time series
- [ ] Convert mortality counts to rates (using populations)

**Comment by crangelsmith** [comment]
I have been looking at the age standardise method. It seems that to calculate it we need the number of people that died by age group, and to those numbers we apply the European age standardisation weight to estimate the rate. There is no way that we can also get the age bin and the week of death, so we need to find a way around it. 

My proposal is to use the data they released on their analysis, that has the estimated rate for local authority (Table 2). https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/deaths/datasets/deathsinvolvingcovid19bylocalareaanddeprivation

We could calculate a weight which would be the ratio between the rate they quote (column L) and the plain rate per 100000 (we would have to estimate it from column K). That weight we use for our standardisation. 

The hypothesis is that that weight will carry most of the information on the age demographic of the local authority, and that the age distribution of people dying from one week to another should not change drastically (we know CODIV kills mostly over 70s, this must be the same in all cases). This is of course not the perfect method, but as we are not the ONS we have to find a way to work with the available information.

Any thoughts?

**Comment by samvanstroud** [comment]
Sounds good @crangelsmith. Do you think we can do both standardisation steps (age + pop) in the same go using a single weight derived by comparing columns K and L? Then we wouldn't even need to look at the population data ourselves.

**Comment by crangelsmith** [comment]
Yeah, good point @samvanstroud, the age-standardised rate has already the population information so we can use it directly in the weight.

**Comment by samvanstroud** [comment]
All the points required are included, let's close this
