### ISSUE TITLE
FOI request for testing data granularity

### ISSUE THREAD

**Issue by kevinxufs** [alan-turing-institute/TuringDataStories#31]

**Comment by kevinxufs** [comment]
It seems that the process of an FOI request is not overly difficult, with most of the guidance here: https://www.gov.uk/make-a-freedom-of-information-request

The important thing I think is for us to be as specific and clear about our question as possible.
Specifically with our testing question there are a number of things to think about:

1) The kinds of tests

2) What location means - testing can be done using home kits, nhs hospitals or testing 'hubs'. 

3) Dates

I suggest something along the lines of:
`What is the location distribution of Covid19 tests during the 2020 March - May period? Please provide location information on the highest granularity possible (ideally by local authority or MSOA). If the data is available, please also split between the type of test (e.g. antibody test) and how it was administered (e.g. home testing kit, testing hub, nhs hospital)`

One thing we should be aware of is that that government departments can reject an FOI request if they can reasonably argue it will have too large administrative cost (£450+). For this reason it might be easier for us so be specific about one thing, for example the regional testing sites locations, or to make seperate requests.

I've found a template for making these requests: https://www.foi.directory/foi-request-template/

Am happy to write a draft letter for our meeting on Wednesday.

Another thing to consider - which government department will we be sending our FOI request to?
I'm assuming it is DHSC, but it could also be the ONS.

To send a FOI request to DSHC we can use: https://contactus.dhsc.gov.uk/

**Comment by kevinxufs** [comment]
**DRAFT**

Dear FOIA officer

I am writing to you under the Freedom of Information Act 2000 to request the following information from the Department of Health and Social Care (DHSC):

'What is the location distribution of Covid19 tests between the 2020 March - May period?'

Please provide location information at the highest granularity available (ideally by local authority or MSOA). Please also split between the type of test (e.g. antibody tests) and how it was administered (e.g. home testing kit, testing hub, nhs hospital).

Please provide this information in the form of a CSV file.

If parts of this request are not available (e.g granularity by local authority or type of test), please can you release what data is available.

If it is not possible to provide the information requested due to the information exceeding the cost of compliance limits identified in Section 12, please provide advice and assistance, under the Section 16 obligations of the Act, as to how I can refine my request.

If you can identify any ways that my request could be refined I would be grateful for any further advice and assistance.

If you have any queries please don’t hesitate to contact me via email or phone and I will be very happy to clarify what I am asking for and discuss the request, my details are outlined below.

Thank you for your time and I look forward to your response.

Yours Faithfully

<insert sign off, contact details etc>

**Comment by samvanstroud** [comment]
Look great Kevin! One comment:

> 'What is the location distribution of UK Covid19 tests between the 2020 March - May period?'

Here instead of "location distribution" (which is potentially a bit ambiguous) I think we could say "number of tests performed each week per geographic region" (or we can omit the "each week" if we think that will have a higher chance of being successful.

**Comment by kevinxufs** [comment]
Thanks Sam - I think you're right in terms of the phrasing as I agree it was a bit confusing.

I think we can ask for each week as long as we have our disclaimer that if weekly is not possible, to release whatever is.

Actually, I've just been searching through DHSC FOI requests and there seems to be someone who has already posted the following FOI request:

https://www.whatdotheyknow.com/request/covid_19_testing_data#incoming-1578229

I think we can still submit our own, but it would make sense to ask for something else. Maybe something more related to deprivation.

**Comment by samvanstroud** [comment]
Hi Kevin, the FOI you have linked does sound like it asks for different data than we are after. In particular they are after antibody tests (which test of immunity i.e. if you have previously had the disease), whereas we are considering "swab" tests (there might be a better name, but these test whether you currently have the disease). 

The effort mentioned in the linked request I think refers to a plan to test a representative sample of the population with the antibody tests, and to use this to work out what percentage of the people in the Country have had the disease. If I understand correctly, that means they are not even trying to test people who have symptoms or are ill, which would be the primary focus of the tests we are interested in.

So perhaps our request is different enough to be valid anyway? What do you think?

**Comment by kevinxufs** [comment]
Thanks Sam.

I originally assumed that we would be interested on full data over the variety of different tests - **including both antibody and swab.** I think you're right though that the linked FOI focuses very specifically on the antibody tests, and that we would still be interested in geographical data for the swab tests.

In that case I think we can continue with our request as is. It would be especially beneficial if we could get data that specifies the kind of test at a given location, so we could see how the swab and antibody tests differ. I'm happy to go ahead and submit this if you guys are happy.

**Comment by samvanstroud** [comment]
Hi @kevinxufs. We talked a little bit more about this just now and had a few more suggestions for refinements:

- We would like both the numbers on number of tests, and also number of people tested if available (many people have more than one test).
- We would ideally like the date of the test, rather than the week in which it was conducted.
- All of that broken down into as small a geographic area as possible (Local Authority, or LSOA). We want the location of where the person who was tested is a resident if possible, otherwise failing that, the location of where the test was conducted.

Cheers!

**Comment by kevinxufs** [comment]
**Refined draft**

Dear FOIA officer

I am writing to you under the Freedom of Information Act 2000 to request the following information from the Department of Health and Social Care (DHSC):

`What are the number of Covid19 tests by geographic area and by date of test?'

Please provide data both on the number of tests and if available, the number of people tested and the type of test (namely, Swab / antibody).

By geographic area, I refer to the residency location of the person who was tested. If that data is not available, then please provide the location of where the test was conducted and ideally, how it was administered (e.g. home testing kit, testing hub, nhs hospital). Please provide this data broken down into as small a geographic area as possible (Local Authority or LSOA).

Please provide this information in the form of a CSV file(s).

If parts of this request are not available (e.g granularity of geographic area or type of test), please can you release what data is available that is as close as possible in line with my request.

If it is not possible to provide the information requested due to the information exceeding the cost of compliance limits identified in Section 12, please provide advice and assistance, under the Section 16 obligations of the Act, as to how I can refine my request.

If you can identify any ways that my request could be refined I would be grateful for any further advice and assistance.

If you have any queries please don’t hesitate to contact me via email or phone and I will be very happy to clarify what I am asking for and discuss the request, my details are outlined below.

Thank you for your time and I look forward to your response.

Yours Faithfully

<insert sign off, contact details etc>

Thoughts? @samvanstroud @crangelsmith @DavidBeavan

**Comment by samvanstroud** [comment]
That looks great to me @kevinxufs, thanks!

**Comment by DavidBeavan** [comment]
@kevinxufs nice, short and sweet.

**Comment by crangelsmith** [comment]
This looks great @kevinxufs , thank you for sorting this out :)

**Comment by kevinxufs** [comment]
Thanks guys - I have now submitted the FOI request to DHSC and received their confirmation email.

20 working days from now seems like the 2nd of July.
