### ISSUE TITLE
Recreate the first ONS plot

### ISSUE THREAD

**Issue by kevinxufs** [alan-turing-institute/TuringDataStories#35]

**Comment by samvanstroud** [comment]
We have recreated the first plot at https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/deaths/bulletins/deathsinvolvingcovid19bylocalareasanddeprivation/latest

However our plot is not the same. (In fact it is very different). I will check the code. 

If we don't find any mistakes, there might be some interesting issues worth discussing around "rewriting history" / research reproducibility.

**Comment by kevinxufs** [comment]
I think that's a good point.

Something Martin mentioned the other day was that our project also has the potential to provide a lot of insight into the issues with Government data and the ability to reproduce that analysis. We should be noting down any of the challenges we have.

One narrative is this: if government are providing analysis and directly attaching the used data to it, why is it so difficult to reproduce their analysis? And how can we be sure that their analysis is correct if it difficult to reproduce?

**Comment by samvanstroud** [comment]
Turned out I had included a bug, so not as hard to reproduce as we thought :) closing this as the first plot has been recreated.
