### ISSUE TITLE
Create a final box plot with comparison operations over different time periods

### ISSUE THREAD

**Issue by kevinxufs** [alan-turing-institute/TuringDataStories#46]

**Comment by crangelsmith** [comment]
I created a summary plot comparing the two time periods, and i found something interesting when comparing the rates of deaths in care home + hospices and everything else:

*Rates in care homes and hospices*:

![image](https://user-images.githubusercontent.com/11162074/85570167-0c093380-b62b-11ea-9472-6c12b45d06a5.png)

*Rates in hospitals and homes*:

![image](https://user-images.githubusercontent.com/11162074/85570416-3ce96880-b62b-11ea-9dc5-fd6bed49cc58.png)

This makes sense, the index of deprivation on the care home area not necessarily affect the residents. So I think our story is in the second figure, where the change in the first bin is significant with respect to the others.
