### ISSUE TITLE
Open Life Science Programme application

### ISSUE THREAD

**Issue by kevinxufs** [alan-turing-institute/TuringDataStories#48]
Open Life Science are organising a programme to help develop open science training skills. There seems to be a collaboration with *The Turing Way*.

The programme lasts for 16 weeks, see [here](https://openlifesci.org/ols-2) for more details.

Application deadline is the **15th of July** 

We should consider making an application.

**Comment by crangelsmith** [comment]
Template for the application https://docs.google.com/document/d/1aCU3DB4tD_nMaSiWDZaK3XGCfaWg1yAU6CQ6fia0-Eg/edit

**Comment by kevinxufs** [comment]
Can be useful for writing the application: https://openlifesci.org/code-of-conduct

**Comment by DavidBeavan** [comment]
Draft is in Google Docs, see invite from @kevinxufs Wednesday, 8 July 2020 at 13:51
