### ISSUE TITLE
Create a logo for Turing Data Stories

### ISSUE THREAD

**Issue by kevinxufs** [alan-turing-institute/TuringDataStories#60]

**Comment by kevinxufs** [comment]
Could be an Hacktoberfest thing.

We understand that Nick in our team has considerable experience - may be worth reaching out to him?

**Comment by samvanstroud** [comment]
<img width="600" alt="TDS-logo-004" src="https://user-images.githubusercontent.com/16232199/98827872-42571c00-242f-11eb-9989-eabd68ac6742.png">
<img width="800" alt="TDS-logo-002" src="https://user-images.githubusercontent.com/16232199/98827878-42efb280-242f-11eb-9ff1-8230d35fb206.png">
