### ISSUE TITLE
Establish Data Story review checklist / set of standards

### ISSUE THREAD

**Issue by kevinxufs** [alan-turing-institute/TuringDataStories#65]
Our current standards according to the README is:

- Turing Data Stories should be detailed and pedagogic jupyter notebooks that document an interesting insight or result using real world data
 - The story should be told in a pedagogical way, describing both the context of the story and the methods used in the analysis.
 - The analysis must be fully reproducible (the notebooks should be able to be ran by others using a defined computer environment).
 - The results should be transparent, all data sources are correctly refered to and included.
 - In order to mantain the quality of the results, the Turing Data Story should be peer-reviewed by other contributors before published.

We should be looking to refine these as we test out different ways to write stories.

**Comment by samvanstroud** [comment]
See #75
