### ISSUE TITLE
Write conclusions and finalise the story

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/TuringDataStories#67]
In our work session of 16th September we decided to us this [hackmd](https://hackmd.io/@VTC7yAqQRpezaQv_KTSPJQ/rkypeo1Bv/edit) to write colaboratively the conclusions of the story:

Things to do before the next Wednesday :

- [x] Read the full story 
- [x] Take notes of things that might get repeated or missing
- [x] Start developing the conclusion based on the points stated originally in the hackmd.

**Comment by kevinxufs** [comment]
Hi all,

Please take a look at the conclusion in the hack md and let me know what you think.

In particular if we are missing any points, but also the general tone / phrasing.

Thanks

**Comment by DavidBeavan** [comment]
I've reviewed and added the conclusion to the notebook, @samvanstroud over to you before we do PR and review

**Comment by samvanstroud** [comment]
I've made some final changes on my end! I think we are ready to start the review.
