### ISSUE TITLE
Create Slack Workspace

### ISSUE THREAD

**Issue by DavidBeavan** [alan-turing-institute/TuringDataStories#74]
### Summary

Create a Slack Workspace to make it easy to communicate and collaborate in an open way, as a community

### What needs to be done?

- [x] Create workspace
- [x] Add initial users
- [ ] Configure look and feel
- [ ] Configure security and permissions
- [ ] Elevate users to admin/owner (only once they have logged in)

### Who can help?

* @DavidBeavan 

---

### Updates

* turingdatastories.slack.com

**Comment by DavidBeavan** [comment]
I'd welcome thoughts on the permissiveness or otherwise of the below:

<img width="925" alt="Screenshot 2020-09-30 at 15 29 32" src="https://user-images.githubusercontent.com/6524799/94699073-d793ca80-0331-11eb-8ba9-a65b3e1d8757.png">

**Comment by crangelsmith** [comment]
Hi @DavidBeavan , i paired the Slack channel with github, so we will get notifications of new issues/PR etc. 

About your post above, i think option 3, 5 and 6 should be for admins and owners only, to make sure we don't loose control of the channel. The rest can be open.

**Comment by DavidBeavan** [comment]
Settings updated 2020-11-11

<img width="815" alt="Screenshot 2020-11-11 at 15 40 09" src="https://user-images.githubusercontent.com/6524799/98832029-3cb00500-2434-11eb-8f3a-f615117f8fd5.png">
