### ISSUE TITLE
Establish the structure and content of the first, example story.

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/TuringDataStories#8]
From the discussion on May 20, a fist data story could be to following:

**Investigate who is dying of Covid19 in the different phases of the epidemic.**

We know from the ONS that people living in more deprived areas are more likely to die of Covid19. In this story we want to see if the distribution of deprivation from people dying changes during the different stages of the epidemic.  The phases of the lockdown would be the following:

1. Phase 1: First 3 weeks after the lockdown is announced, people dying in this period got Covid19 in their normal routines. 
2. Phase 2: From the 3 weeks after the lockdown until  3 weeks after first relaxations, people dying in this period got Covid19 during lockdown. 
3. Phase 3: From the fist 3 weeks after fists relaxation of restrictions, people dying in this period got Covid19 when going back to work?

The hypothesis is that people living in more deprived areas had to keep working during lockdown or had to go back to work in phase 3. This means that the general distribution of deprivation from people dying will change between phases, we need to see relative changes and not absolute numbers becase those will depend on where we were on the curve.

A good comparison would be to do the same analysis with data from Scotland where the lockdown has been more strict and relaxations are happening later.

Data sources to use: 
- Dead registrations for England and Wales (this data is updated weekly): https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/deaths/datasets/weeklyprovisionalfiguresondeathsregisteredinenglandandwales
- Indexes of deprivations for England and Wales: https://www.gov.uk/government/statistics/english-indices-of-deprivation-2019
- Data from Scotland: Need to find sources.

**Comment by kevinxufs** [comment]
Story / Narrative / Hypothesis:
Data:
Technologies:
Analysis:
Further explanation:

**Comment by kevinxufs** [comment]
> 
> 
> From the discussion on May 20, a fist data story could be to following:
> 
> **Investigate who is dying of Covid19 in the different phases of the epidemic.**
> 
> We know from the ONS that people living in more deprived areas are more likely to die of Covid19. In this story we want to see if the distribution of deprivation from people dying changes during the different stages of the epidemic. The phases of the lockdown would be the following:
> 
>     1. Phase 1: First 3 weeks after the lockdown is announced, people dying in this period got Covid19 in their normal routines.
> 
>     2. Phase 2: From the 3 weeks after the lockdown until  3 weeks after first relaxations, people dying in this period got Covid19 during lockdown.
> 
>     3. Phase 3: From the fist 3 weeks after fists relaxation of restrictions, people dying in this period got Covid19 when going back to work?
> 
> 
> The hypothesis is that people living in more deprived areas had to keep working during lockdown or had to go back to work in phase 3. This means that the general distribution of deprivation from people dying will change between phases, we need to see relative changes and not absolute numbers becase those will depend on where we were on the curve.
> 
> A good comparison would be to do the same analysis with data from Scotland where the lockdown has been more strict and relaxations are happening later.
> 
> Data sources to use:
> 
>     * Dead registrations for England and Wales (this data is updated weekly): https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/deaths/datasets/weeklyprovisionalfiguresondeathsregisteredinenglandandwales
> 
>     * Indexes of deprivations for England and Wales: https://www.gov.uk/government/statistics/english-indices-of-deprivation-2019
> 
>     * Data from Scotland: Need to find sources.

This looks really good to me.

I think the only thing to add is to consider a bit about how we are going to do this i.e. how we will use the data to answer our hypothesis.

Presumably we will want to provide some kind of similar and comparable analysis to the NHS. So this would involve some **data visualisation techniques**. 

We also know that the data was not completely ideal and thus we will need to do some **data wrangling**

And then we also will have to use different **data analysis techniques** to see whether England for example is different to the other nations that have not relaxed the lockdown.

I think it would be good to discuss this in the tech talk as it adds to the pedagogical story - we walk the user through different steps required to answer our hypothesis.

**Comment by samvanstroud** [comment]
> Data from Scotland: Need to find sources.

I had a quick look. Strangely https://www.gov.scot/ (from Google search results there might be something there). 

There is also this page:
https://www.nrscotland.gov.uk/statistics-and-data/statistics/statistics-by-theme/vital-events/general-publications/weekly-and-monthly-data-on-births-and-deaths/deaths-involving-coronavirus-covid-19-in-scotland

Which links to the following open dataset (API seems to be availible). At the bottom of the page you can download the entire dataset in csv. 
https://statistics.gov.scot/data/deaths-involving-coronavirus-covid-19

Column headings are:
FeatureCode (location) | DateCode | Measurement | Units | Value | Sex | Age | Cause Of Death | Location Of Death

**Comment by samvanstroud** [comment]
@crangelsmith this dataset:

> Data sources to use:
> - Dead registrations for England and Wales (this data is updated weekly): https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/deaths/datasets/weeklyprovisionalfiguresondeathsregisteredinenglandandwales

Does not contain a spatial breakdown of mortality, right? So we either have to choose between loosing spatial information, but getting time series information (above dataset), or using this dataset: https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/deaths/datasets/deathsinvolvingcovid19bylocalareaanddeprivation, which is broken down spatially, but does not have a time axis.

**Comment by samvanstroud** [comment]
To clear up the above comment, the dataset we want is 

https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/causesofdeath/datasets/deathregistrationsandoccurrencesbylocalauthorityandhealthboard

which contians a time series and spatial breakdown. Thanks @crangelsmith.

**Comment by samvanstroud** [comment]
I think we have a relatively good idea of what we are including in the story. We are going to replicate the ONS analysis, and also add a time axis. We are then going to see if the three stages of lockdown (pre, during, post) show differing effects on local mortality rates as a function of depravation.
