### ISSUE TITLE
Get new voluntaries from REG to work with us in the project.

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/TuringDataStories#92]
### Summary

Try to recruit new members from REG or fast streamers. We could use the REG hack session in #91 to ask people to join us as project maintainers.

### Who can help?

* @DavidBeavan :) 

---

**Comment by samvanstroud** [comment]
WIP reachout message (via @crangelsmith) https://hackmd.io/NpDeoXefTgyqh7m1k853aA

**Comment by samvanstroud** [comment]
See #83
