### ISSUE TITLE
Draft structure for OLS presentation

### ISSUE THREAD

**Issue by DavidBeavan** [alan-turing-institute/TuringDataStories#99]
Create an outline, with:
* Demo the project
* Inspire others
* Show how OLS-2 has helped

https://hackmd.io/n3I9LA0EROKhKe06HdAmpA?both

**Comment by kevinxufs** [comment]
Additional comments on things we found useful:

Contributor personas,

Cohort calls

Reminder on good practice 

Engaging with the community

**Comment by kevinxufs** [comment]
Hi @DavidBeavan @crangelsmith @samvanstroud 

I had a bit this afternoon to work on the presentation and have a first draft - I'm not quite sure how to link it, I think it is in Dave's share point?

A few slides are still lacking a bit of detail (e.g. challenges and learnings) but hopefully this is a good start.
Let me know if you think the structure / content etc should be changed

Thanks

Kevin
